# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
      # cassandra not work yet
      - image: circleci/cassandra:3.10
        environment:
          JAVA_OPTS: -Xloggc:/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=3
    steps:
      - checkout
      - run: gradle clean test
      - run: gradle build jacocoTestReport sonarqube